version: "3.2"
services:
  rabbiting:
    image: rabbitmq:4.0-management
    container_name: 'rabbitmq'  
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbiting/data/:/var/lib/rabbiting/
      - ~/.docker-conf/rabbiting/log/:/var/log/rabbiting
    networks:
      - rabbiting_nodejs

networks:
  rabbiting_nodejs:
    driver: bridge

# mongodb:
#   image: mongo
#   ports:
#     - "27017:27017"